#!/usr/bin/env bash

DOTFILES_DIR="$HOME/dotfiles"

packages=(
	"nvim"
	"tmux"
	"zsh"
	"bin"
)

# Install stow if it doesnt exist
if ! command -v stow &>/dev/null; then
	echo "GNU Stow not found. Attempting to install..."
	if [ -f /etc/debian_version ]; then
		sudo apt update
		sudo apt install -y stow
		echo "GNU Stow installed"
	else 
		echo "Unsupported system. Please install GNU stow"
		exit 1
	fi
fi

cd "$DOTFILES_DIR" || { echo "Error: Could not find dotfiles directory"; exit 1; }

for package in "${packages[@]}"; do 
	echo "Installing $package..."
	stow -v "$package"
done

echo "Dotfiles installed successfully!"

exit 0
