#!/usr/bin/env bash

DOTFILES_DIR="$(realpath "$HOME/dotfiles")"
TARGET_DIR="$(realpath "$HOME")"
TPM_DIR="$DOTFILES_DIR/tmux/.config/tmux/plugins/tpm"

packages=(
	"nvim"
	"tmux"
	"zsh"
	"bin"
)

uninstall=false
if [ "$1" == "-x" ]; then
	uninstall=true
fi

# Install stow if it doesnt exist
if ! command -v stow &>/dev/null; then
	if [ -f /etc/debian_version ]; then
        echo "Installing GNU stow..."
		sudo apt update
		sudo apt install -y stow
		echo "GNU Stow installed"
	else
		echo "Unsupported system. Please install GNU stow"
		exit 1
	fi
fi

cd "$DOTFILES_DIR" || { echo "Error: Could not find dotfiles directory"; exit 1; }

if [ "$uninstall" = true ]; then
    echo "Uninstalling packages..."
    for package in "${packages[@]}"; do
        echo "Uninstalling $package..."
        stow -D -v --dir="$DOTFILES_DIR" --target="$TARGET_DIR" "$package"
    done
    echo "Dotfiles uninstalled successfully!"
    exit 0
else
    # Install packages
    for package in "${packages[@]}"; do
        echo "Installing $package..."
        stow -v --dir="$DOTFILES_DIR" --target="$TARGET_DIR" "$package"
    done

    if [ ! -d "$TPM_DIR" ]; then
        git clone https://github.com/tmux-plugins/tpm $TPM_DIR
        tmux source "$DOTFILES_DIR/tmux/.config/tmux/tmux.conf"
        echo "TPM installed successfully!"
    else
        echo "TPM is already installed."
    fi

    echo "Installing Tmux plugins..."
    if [ -n "$TMUX" ]; then
        # In Tmux session
        "$TPM_DIR/bin/install_plugins"
        echo "Tmux plugins installed successfully"
    else
        # We're not inside a Tmux session
        tmux start-server && tmux new-session -d
        "$TPM_DIR/bin/install_plugins"
        tmux kill-server
        echo "Tmux plugins installed successfully"
    fi

    echo "Dotfiles installed successfully!"

    exit 0
fi
